

SHOW FULL PROCESSLIST;


CREATE DATABASE IF NOT EXISTS `docker_connect`;
USE `docker_connect`;

CREATE TABLE IF NOT EXISTS `docker_connect`.`access_log`(
 `id` INT NOT NULL AUTO_INCREMENT ,
 `request_data` VARCHAR(5000) ,
 `access_timestamp` TIMESTAMP , PRIMARY KEY (`id`) );

CREATE USER 'npatel'@'%' IDENTIFIED BY 'namrata';
GRANT ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TABLESPACE,
CREATE TEMPORARY TABLES, CREATE USER, CREATE VIEW, DELETE, DROP, EVENT, EXECUTE,
FILE, INDEX, INSERT, LOCK TABLES, PROCESS, REFERENCES, RELOAD, REPLICATION CLIENT,
REPLICATION SLAVE, SELECT, SHOW DATABASES, SHOW VIEW, SHUTDOWN, SUPER, TRIGGER,
UPDATE ON *.* TO 'npatel'@'%' WITH GRANT OPTION;


DESCRIBE `docker_connect`.`access_log`;